### ISSUE TITLE
Please provide a NuGet package

### ISSUE THREAD

**Issue by ghost** [RudyTheDev/SharpVoronoiLib#8]
The project has been written in the JetBrains' IDE, with lots of `using`s and annotations that don't exist within Visual Studio. Cleaning up the code becomes a small (but repeated) hassle whenever we download the library to use within our projects; the project could greatly benefit from a NuGet release, since the binaries are IDE-agnostic.

**Comment by RudyTheDev** [comment]
Hi! I've been meaning to do this forever and just never got around to it. Anyway, I set up the project for NuGet package publishing and it seems to be available/work now: https://www.nuget.org/packages/SharpVoronoiLib. Let me know if there are any issues with it.

**Comment by ghost** [comment]
Thank you! I'll give it a shot and if anything happens I'll update you here :D
